In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])  
print(a)
print(type(a))


[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

array=np.array([[1,2,3],[4,5,6]])
print (array)
print (array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
import numpy as np

array=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print (array)
print ()
print (array.shape)


[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]

(2, 2, 3)


In [19]:
import numpy as np

array=np.array([[[1,2,3,8],[4,5,6]],[[8,4,5],[7,8,9]]])
print (array)
print ()
print (array.shape)
print(array.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [20]:
import numpy as np

array = np.array([[[1, 2, 3], [4, 5, 6]], [[8, 4, 5], [7, 8, 9]]])
print(array)


[[[1 2 3]
  [4 5 6]]

 [[8 4 5]
  [7 8 9]]]


In [ ]:
print(array.ndim) #number of dimensions of an array.

3
