In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])  
print(a)
print(type(a))


[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

array=np.array([[1,2,3],[4,5,6]])
print (array)
print (array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
import numpy as np

array=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print (array)
print ()
print (array.shape)


[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]

(2, 2, 3)


In [19]:
import numpy as np

array=np.array([[[1,2,3,8],[4,5,6]],[[8,4,5],[7,8,9]]])
print (array)
print ()
print (array.shape)
print(array.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [20]:
import numpy as np

array = np.array([[[1, 2, 3], [4, 5, 6]], [[8, 4, 5], [7, 8, 9]]])
print(array)


[[[1 2 3]
  [4 5 6]]

 [[8 4 5]
  [7 8 9]]]


In [24]:
import numpy as np

array = np.array([1, 9, 3])
print (array[1])


9


In [25]:
import numpy as np

array=np.array([[1,2,3],[4,5,6]])

print(array[1, 2])

6


In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]])
print(-2,-1)




-2 -1


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])
condition = (arr > 25) && (arr<=50)

print(condition)
print(arr[condition])




[False False  True  True]
[30 40]


In [ ]:
array = np.zeros(5)
print(array)



[0. 0. 0. 0. 0.]


In [36]:
array = np.zeros((2,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
array = np.full((2,4),5)
print(array)

[[5 5 5 5]
 [5 5 5 5]]


In [3]:
import numpy as np

array = np.empty((2, 3))
print(array)


[[-6.95267200e-310  2.04234319e+297  7.74302805e-312]
 [ 7.74302805e-312  9.38724727e-323  2.51973479e-322]]


In [13]:
import numpy as np

arr = np.arange(1, 21)
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

arr_2 = np.array([11, 10, 20, 30, 40, 50])
mean = np.mean(arr_2)
greater_than_mean = arr_2[arr_2 > mean]
print(greater_than_mean)


[ 2  4  6  8 10 12 14 16 18 20]
[30 40 50]
